version: '3'
volumes:
  static:
services:
  python:
    build:
      dockerfile: docker/prod/python/Dockerfile
    env_file:
      - ./env_vars/prod_app.env
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.prod
    volumes:
      - static:/home/tester/static
    command: gunicorn -w 4 app.wsgi -b 0.0.0.0:8000

  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static:/static
    ports:
     - 8080:80
